DROP TABLE IF EXISTS groceryList;

CREATE TABLE groceryList (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    title TEXT NOT NULL,
    type TEXT NOT NULL
);